### ISSUE TITLE
Instructions for Linux

### ISSUE THREAD

**Issue by Mebus** [latonita/arduino-canbus-monitor#10]
Hallo,

on Linux I used the follow instructions to create a `can0` device in conjunction with `sudo`:

```
slcan_attach -f -s4 -o /dev/ttyUSB0
slcand -S 115200 /dev/ttyUSB0 can0  
ifconfig can0 up 
```
To dump the running traffic the following command can be used

```
candump can0
```

To delete the interface the following commands can be used:

```
ifconfig can0 down
killall slcand
```

On Debian or Ubuntu this command:

```
apt install can-utils
```
installs the neccessary packages.

Can you please add theses instructions to the Readme? :smiley: 

Mebus

**Comment by Mebus** [comment]
And thanks for the great code, it works quite nice with my PLC! :grinning:

**Comment by latonita** [comment]
Thank you for feedback. I'm glad it helps people!
