### ISSUE TITLE
CanPlayer Not working

### ISSUE THREAD

**Issue by seeklakhan** [latonita/arduino-canbus-monitor#13]
So i have connected wires in this manner i'm able to do candamp can0 and receive packets correctly.   

![shot](https://user-images.githubusercontent.com/101640203/191240683-beaf55c4-7680-4f14-9dce-1c75bd03cb90.jpg)

so i did candamp -l can0

and when I'm doing canplayer -I file.log it's not working :(

**Comment by latonita** [comment]
Hi, i think you may try to record this way:
`candump -L can0 > myfile.log`
and then play it
`canplayer -I myfile.log`

**Comment by seeklakhan** [comment]
candump -l file.log is also working fine i'm receiving CAN frames but its not performing actions on transmitting those frames like blinker turn on/off lights etc... 
although 
I also tried 
candump -L can0 > myfile.log
canplayer -I myfile.log

still the same results 

I have also done 
sudo ifconfig can0 txqueuelen 1000

so in simple words reply frame is not working 

@latonita

**Comment by seeklakhan** [comment]
I noticed one thing more, i'm only receiving CAN data when car is started not on idle mode. in idle mode i should also received data right? when i press blinker etc... ? @latonita waiting for your reply

**Comment by latonita** [comment]
@seeklakhan i think you shall receive CAN data when you insert a key and turn it to ACC or ON mode. I can't remember data coming in OFF position

**Comment by seeklakhan** [comment]
@latonita so do you have any idea why am I not getting blinker, window, lights etc... CAN frames? i also tried reply attack on these items but reply attack is also not working any idea ?

**Comment by latonita** [comment]
@seeklakhan hm... that depends on the car and on where do you connect - to which can bus.
typically there are several segments of can bus and between them are gateways which decide which messages go though, which are not.
In my particular case Jeep Grand Ch. 2005 - I connect to "Interior CAN" which is low speed and connected to ECU via firewall of some kind. Although it receives some info on blinkers and other stuff since dashboard is also connected.

Check your car's wiring diagrams.

**Comment by seeklakhan** [comment]
@latonita these are my connected ports I have tested PIN 6 and 14 although i'm receiving data but i don't think i'm getting complete data what do you think which other PIN should i try ?

[](url)   
![IMG20220407140636](https://user-images.githubusercontent.com/101640203/193242776-032458af-2379-4a4b-8218-85fe6e94e4e9.png)

**Comment by latonita** [comment]
what is this port? i have no idea)
if its OBD port near the wheel - then it is behind extra firewall typically)

**Comment by seeklakhan** [comment]
@latonita yes its OBD port and I have checked one thing more today I'm getting CAN Low packets on pin 11. but when i'm doing replay attack or cansend its Not working i think you are right! there is firewall so how can bypass firewall ?

**Comment by latonita** [comment]
@seeklakhan you need to find another way to connect to CAN bus, not via OBD port

check your car's service manual, find which modules connected to low speed CAN bus and connect
