### ISSUE TITLE
Thanks a bunch for this its been great!

### ISSUE THREAD

**Issue by hayden-t** [latonita/arduino-canbus-monitor#3]
just what i needed. Also do you know, does your can filter/mask work only in software ? why not use the hardware filtering options ?

**Comment by latonita** [comment]
Great that you liked that.

Yes, there are hardware filter/masks, typically there is way to configure them through can analyser tools - i havent seen any which supports mcp2515+2551 chipset. So there is nothing in API for that. 

Basically you always need to change sketch to update filtering options. For me it worked out just to have pure software filter, there was no need to read through mcp datasheets to understand how to work with hardware filters.

However i have seen it was implemented somewhere. If there will be requests for that i might implement that. Or it might an interesting thing for someone to invest and work on it and the to pull into this main branch :)

Again, i'm glad you liked project. Spread a word.
