### ISSUE TITLE
Weird Issue on receiving data

### ISSUE THREAD

**Issue by mjs513** [latonita/arduino-canbus-monitor#7]
This is kind of weird for me to explain but here goes.  When I first open the monitor the data is happily streaming away.  If I do close "C" say to change the CAN rate say with an "S8"  it returns fine with a CR as it should.  Now if do an "O" nothing happens.  I tried say with a "P" or "A" but then I get the bell.  Now if I put it in listen only mode "L" and send a "P" it does a CR but do not see any data.    I know data is still streaming because I can see it.

What am I doing wrong, help :)
Mike

**Comment by mjs513** [comment]
Hi Anton
Just to let you know I finally got it working = had to change some int8u;s to int32u's.  My new version works the Teensy 3.x series of processors.  I the version I am using here: https://github.com/mjs513/Teensy_Canbus_Monitor_IFCT/blob/master/README.md.  Let me know if there are any issues.

Thanks
This really works like a charm for my purposes

Mike

**Comment by latonita** [comment]
Hello Mike
Thanks for reporting an issue. Unfortunately I'm off for week and coudn't/can't look into this deeper at the moment. 
I'm glad you make it work! 
I will definitely take a look at this bug, root cause and solution in a day or two!!
