### ISSUE TITLE
CAN-BUS_Shield_V2.0

### ISSUE THREAD

**Issue by dews** [latonita/arduino-canbus-monitor#8]
For [CAN-BUS_Shield_V2.0](http://wiki.seeedstudio.com/CAN-BUS_Shield_V2.0/), they change cs pin 10 to pin 9.
So you need to change this line:
https://github.com/latonita/arduino-canbus-monitor/blob/942138d09f73051439cf657aa8e4a201187dd83b/arduino-canbus-monitor/can-232.h#L29

And the debug pin 8 and 9 is conflicted
https://github.com/latonita/arduino-canbus-monitor/blob/942138d09f73051439cf657aa8e4a201187dd83b/arduino-canbus-monitor/can-232.cpp#L26

This is a great project, saving me a lot of time. Thank you.

**Comment by Jimmy062006** [comment]
You can change what Pin is used.

Search the page for the below.

SPI_CS pin of V1.2 is connected to D9 by default. If you want to change to D10, please follow below instructions.

This should probably be closed.
